application: dan-bamberger
version: 1
runtime: python
api_version: 1

handlers:
- url: /i
  static_dir: images

- url: /s
  static_dir: scripts

- url: /
  static_files: main.html
  upload: main.html

